[username]
format = " [$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold red"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

[directory]
style = "purple"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

[sudo]
disabled = false

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "white"

[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1


[battery]
charging_symbol = ""
disabled = true
discharging_symbol = ""
full_symbol = ""

disabled = false
style = "bold red"
threshold = 15

[[battery.display]]
disabled = true
style = "bold yellow"
threshold = 50

[[battery.display]]
disabled = true
style = "bold green"
threshold = 80

[time]
disabled = true
format = " 🕙 $time($style)\n"
style = "bright-white"
time_format = "%T"

[character]
error_symbol = " [×](bold red)"
success_symbol = " [>](bold red)"

