# Hist conf
HISTFILE=$HOME/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000

# Antigen
source $HOME/.config/zsh/antigen.zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen theme denysdovhan/spaceship-prompt

SPACESHIP_USER_SHOW=always

antigen apply

# Node version manager
eval "$(fnm env)"

# Variables
export BAT_THEME="Nord"

# Aliases
alias ls="exa"
alias la="exa -laTL 1"
alias tree="exa -T"
alias vim="nvim"
alias cat="bat"
alias grep="rg"

neofetch --ascii $HOME/.config/neofetch/avatar.tiny.txt
